server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod_db
    username: prod_user
    password: prod_password

custom:
  app-name: "MyApp - Prod"
  api-key: "prod-9876-5432"
  feature-flag: false
